### ISSUE TITLE
patch to support i18n

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_git_blame#12]
File from Markus F.:
[patches.zip](https://github.com/ThaiDat/cuda_git_blame/files/11353443/patches.zip)

Comment from Markus

>Please not that some normal formatted strings are replaced with
f-strings only because the author already uses f-strings in other places.

Comment from me: I prefer to remove f-strings. to support older Python versions, e.g. 3.5. CudaText/WinXP uses Py 3.4.

**Comment by ThaiDat** [comment]
Sorry, I don't know much about i18n. So, if we unify the string style (all f-string or all normal formatted string) will the i18n work. Is this the main purpose of this patch?

> I prefer to remove f-strings. to support older Python versions, e.g. 3.5. CudaText/WinXP uses Py 3.4.

I will convert all to normal formatted strings to support older versions. But, I am on a vacation now and don't have access to my computer. There may be some delay.

**Comment by Alexey-T** [comment]
i18n is not connected with string-style. 2 separate questtions.
patch is to support i18n. ie to support translation of plugin via language-files.

**Comment by ThaiDat** [comment]
The only thing I can see in the file you sent is to convert from normal formatted string to f string. And in this issue, you want to convert everything in current code to normal formatted strings to support older Python, right?

**Comment by Alexey-T** [comment]
now I saw the patch. yes, only thing it does is making f-strings. useless for us. don't apply. instead, remove f-strings from all the code.
