### ISSUE TITLE
Format "Blame analyze file" align number and percentage

### ISSUE THREAD

**Issue by ThaiDat** [ThaiDat/cuda_git_blame#19]
Currently observed:
![image](https://github.com/ThaiDat/cuda_git_blame/assets/18527312/ca11c058-6219-4684-977d-b5059b919597)

Expected:
Numbers and percentage are well aligned

**Comment by Alexey-T** [comment]
why to align them, if names and emails are not aligned?

**Comment by ThaiDat** [comment]
I have organized information by column in another command "See File History"
![image](https://github.com/ThaiDat/cuda_git_blame/assets/18527312/fd8e1fe8-1611-4270-9741-03b277c01f0a)
 This column based format make it easier to see the information.

Want to apply to this command too.
